language: node_js
node_js:
  - "stable"

branches:
  only:
    - main

cache:
  directories:
    - node_modules

install:
  - npm ci || npm install

script:
  - npm run build
  - cp build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  keep_history: true
  on:
    branch: main
