name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Git info
        run: |
          git --version
          echo "Branch: $GITHUB_REF"

      - name: Basic CI step
        run: echo "✅ CI is running for COMP3104"





